### ISSUE TITLE
Parser crashing

### ISSUE THREAD

**Issue by wingoku** [vsavko/Leetcode-parser#1]
I'm using your parser code with the specified fields populated. When I try to run the code in intellij, it gives me the following error:

**I'm using Chrome Driver 88.0.4324.96 & Chrome Dev browser: 90.0.4421.5**

```
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
[1614170662.597][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
[1614170662.597][WARNING]: Deprecated chrome option is ignored: useAutomationExtension
Starting ChromeDriver 88.0.4324.96 (68dba2d8a0b149a1d3afac56fa74648032bcf46b-refs/branch-heads/4324@{#1784}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
Invalid --log-level value.
Unable to initialize logging. Exiting...
Exception in thread "Thread-0" org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: was killed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location path\to\chromedriver.exe is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'computer_name', ip: 'public ip', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '12.0.2'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	GetHandleVerifier [0x00A3B963+483]
	GetHandleVerifier [0x00A3B941+449]
	GetHandleVerifier [0x00DE3308+3832712]
	GetHandleVerifier [0x00DF9FA6+3926054]
	GetHandleVerifier [0x00DF7D9C+3917340]
	GetHandleVerifier [0x00E1E7FE+4075646]
	GetHandleVerifier [0x00E1E56C+4074988]
	GetHandleVerifier [0x00E1B2EB+4062059]
	GetHandleVerifier [0x00DFED14+3945876]
	GetHandleVerifier [0x00DFFBCE+3949646]
	GetHandleVerifier [0x00DFFB59+3949529]
	Ordinal0 [0x009FB5CC+46540]
	Ordinal0 [0x009F9F53+40787]
	Ordinal0 [0x009F9B12+39698]
	GetHandleVerifier [0x00D01468+2907368]
	GetHandleVerifier [0x00B471EE+1096302]
	GetHandleVerifier [0x00B03E8D+821005]
	GetHandleVerifier [0x00B0396B+819691]
	GetHandleVerifier [0x00B03881+819457]
	GetHandleVerifier [0x00B2F463+998627]
	BaseThreadInitThunk [0x75136359+25]
	RtlGetAppContainerNamedObjectPath [0x77728944+228]
	RtlGetAppContainerNamedObjectPath [0x77728914+180]

	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:157)
	at Parser$1.run(Parser.java:195)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by vsavko** [comment]
I'm not sure if the chrome driver will work correctly with the "Chrome Dev browser". Can you try to download the "normal" chrome browser and then use the driver with the applicable version number? 
You can check for the drivers here: https://sites.google.com/a/chromium.org/chromedriver/downloads
